contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #nfpracticum channel"
    url: https://nfcore.slack.com/channels/nfpracticum
    about: Discussion about the nf-core/nfpracticum pipeline
